config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :favorites

  resources :courses
  resources :images
  # root 'students#index'
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  get '/students/help' => 'students#help', as: :help
  get '/students/upload' => 'students#upload', as: :upload
  resources :students

  resources :students do
    get 'help', on: :collection
    get 'upload', on: :collection
  end

  resources :students do 
    collection { post :import }
  end

  resource :students do 
    member do
      post :favor
    end
  end

  resource :courses do 
    member do
      post :delc
    end
  end

  resources :images do 
    collection { post :import }
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    has_many :student
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: %i[ show edit update destroy ]

  # GET /favorites or /favorites.json
  def index
    @favorites = Favorite.all
  end

  # GET /favorites/1 or /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites or /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully created." }
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1 or /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to favorite_url(@favorite), notice: "Favorite was successfully updated." }
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1 or /favorites/1.json
  def destroy
    @favorite.destroy

    respond_to do |format|
      format.html { redirect_to favorites_url, notice: "Favorite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favorite_params
      params.require(:favorite).permit(:lastname, :firstname, :uin, :email, :classname, :notes, :major, :finalgrade, :updatedgrade, :recletter, :semester, :year)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :uin %>
    <%= form.text_field :uin %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :classname %>
    <%= form.text_field :classname %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="field">
    <%= form.label :major %>
    <%= form.text_field :major %>
  </div>

  <div class="field">
    <%= form.label :finalgrade %>
    <%= form.text_field :finalgrade %>
  </div>

  <div class="field">
    <%= form.label :updatedgrade %>
    <%= form.text_field :updatedgrade %>
  </div>

  <div class="field">
    <%= form.label :recletter %>
    <%= form.text_field :recletter %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Show', @favorite %> |
<%= link_to 'Back', favorites_path %>

app/views/favorites/index.html.erb
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
  min-height:100%;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width: 80%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
</style>
</head>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>



<body>
<div class="main">
    <div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%; margin-bottom:3%;">
      <p class="notice" id="notice"><%= notice %></p>

      <h1 style="text-align:center; font-size: 100px; color:#450012" class="text-uppercase">Favorites Page</h1>
      <h3 style="text-align:center; color:#450012">List of favorited students</h3>

    </div>

  <div style="overflow-x:auto;">
    <table style="border:1px solid; border-color: #450012; width:50%; margin-bottom:5%;" class="center">
      <thead>
        <tr style="background-color: white;">
          <th>Lastname</th>
          <th>Firstname</th>
          <th>Uin</th>
          <th>Email</th>
          <th>Classname</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @favorites.each do |favorite| %>
          <tr>
            <%= Student.all.where(uin: favorite.uin, classname: favorite.classname, semester: favorite.semester, year: favorite.year).find_each do |student| %>
              <td><%= student.lastname %></td>
              <td><%= student.firstname %></td>
              <td><%= student.uin %></td>
              <td><%= student.email %></td>
              <td><%= student.classname %></td>
              <td><%= button_to 'Unfavorite', favor_students_path(:lastname => student.lastname, :firstname => student.firstname, :uin => student.uin, :email => student.email, :classname => student.classname, :notes => student.notes, :major => student.major, :finalgrade => student.finalgrade, :updatedgrade => student.updatedgrade, :recletter => student.recletter, :semester => student.semester, :year => student.year), :class => "btn buttonTo" %></td>
              <td><%= link_to 'Show', student, class: "btn buttonTo"%></td>
              <td><%= link_to 'Edit', edit_student_path(student), class: "btn buttonTo" %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="footer">
	<p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
</div>
</body>


app/views/favorites/new.html.erb
<h1>New Favorite</h1>

<%= render 'form', favorite: @favorite %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @favorite.lastname %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @favorite.firstname %>
</p>

<p>
  <strong>Uin:</strong>
  <%= @favorite.uin %>
</p>

<p>
  <strong>Email:</strong>
  <%= @favorite.email %>
</p>

<p>
  <strong>Classname:</strong>
  <%= @favorite.classname %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @favorite.notes %>
</p>

<p>
  <strong>Major:</strong>
  <%= @favorite.major %>
</p>

<p>
  <strong>Finalgrade:</strong>
  <%= @favorite.finalgrade %>
</p>

<p>
  <strong>Updatedgrade:</strong>
  <%= @favorite.updatedgrade %>
</p>

<p>
  <strong>Recletter:</strong>
  <%= @favorite.recletter %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @favorite.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @favorite.year %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>