config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :favorites

  resources :courses
  resources :images
  # root 'students#index'
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  get '/students/help' => 'students#help', as: :help
  get '/students/upload' => 'students#upload', as: :upload
  resources :students

  resources :students do
    get 'help', on: :collection
    get 'upload', on: :collection
  end

  resources :students do 
    collection { post :import }
  end

  resource :students do 
    member do
      post :favor
    end
  end

  resource :courses do 
    member do
      post :delc
    end
  end

  resources :images do 
    collection { post :import }
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  has_one :image
  has_many :course
  has_many :favorite

  # validates :email, presence: true
  # validates :firstname, presence: true
  # validates :lastname, presence: true
  # validates :notes, presence: true
  # validates :uin, presence: true
  # validates :major, presence: true
  # validates :finalgrade, presence: true
  # validates :updatedgrade, presence: true
  validates :classname, presence: true
  # validates :recletter, presence: true
  validates :semester, presence: true
  validates :year, presence: true
  
  # csv upload
  def self.import(file, year, semester, files, classn)
    i = 0
    # sort images

    # create course if not already created?
    check = false
    if Course.all.count >= 1
      logger.info "\n\n HERE1 \n\n"
      Course.all.each do |course|
        if course.classname == classn && course.semester == semester && course.year == year
          check = true
          logger.info "\n\n HERE2 \n\n"
        end
      end
    end

    if not(check)
      course_hash = Course.new
      course_hash.classname = classn
      course_hash.semester = semester
      course_hash.year = year
      course_hash.save
    end

    CSV.foreach(file, headers: true) do |row|
      # create the image instance for each student
      image_hash = Image.new
      image_hash.uin = row[3]
      image_hash.photo.attach(files[i])
      i += 1
      image_hash.save

      # create the student for each csv entry
      student_hash = Student.new
      student_hash.lastname = row[0]
      student_hash.firstname = row[1]
      student_hash.uin = row[3]
      student_hash.email = row[5]
      student_hash.classname = classn
      student_hash.notes = row[8]
      student_hash.major = row[9]
      student_hash.finalgrade = row[14]
      student_hash.updatedgrade = row[15]
      student_hash.recletter = 'undecided'
      student_hash.semester = semester.to_s
      student_hash.year = year
      student_hash.save
    end
    # redirect_to students_path, notice: "Students Imported Successfully"
  end
  
  def self.favor(lastname, firstname, uin, email, classname, notes, major, finalgrade, updatedgrade, recletter, semester, year)
    if Favorite.all.where(uin: uin).find_each.count < 1
      favorite_hash = Favorite.new
      favorite_hash.lastname =  lastname
      favorite_hash.firstname =  firstname
      favorite_hash.uin = uin
      favorite_hash.email = email
      favorite_hash.classname = classname
      favorite_hash.notes =  notes
      favorite_hash.major = major
      favorite_hash.finalgrade =  finalgrade
      favorite_hash.updatedgrade = updatedgrade
      favorite_hash.recletter = recletter
      favorite_hash.semester = semester
      favorite_hash.year = year
      favorite_hash.save
    else
      Favorite.all.find_by(uin: uin).destroy
    end
  end

  def next
    self.class.where("id < ?", id).last
  end

  def previous
    self.class.where("id > ?", id).first
  end 



end

app/controllers/students_controller.rb

# frozen_string_literal: true

class StudentsController < ApplicationController
  before_action :set_student, only: %i[show edit update destroy]
  # skip_before_action :verify_authenticity_token, only: [:import]

  # GET /students or /students.json
  def index
    @q = Student.ransack(params[:q])
    @students = @q.result
    
    @images = Image.all
    if params[:search_by_firstname] && params[:search_by_firstname] != ''
      @students = @students.where('firstname ~* ?',
                                  params[:search_by_firstname])
    end
    if params[:search_by_lastname] && params[:search_by_lastname] != ''
      @students = @students.where('lastname ~* ?',
                                  params[:search_by_lastname])
    end
    if params[:search_by_recletter] && params[:search_by_recletter] != ''
      @students = @students.where('recletter ~* ?',
                                  params[:search_by_recletter])
    end
  end

  # GET /students/1 or /students/1.json
  def show
    @students = Student.all
    @Images = Image.all

    @favorites = Favorite.all

    @student = Student.all.find(params[:id])
    @previous_student = @student.next
    @next_student = @student.previous

  end

  # GET /students/new
  def new
    @student = Student.new
    @Images = Image.all
  end

  # GET /students/1/edit
  def edit
    @Images = Image.all
  end

  # POST /students or /students.json
  def create
    @courses = Course.all
    @student = Student.new(student_params)

    check = false

    if @courses.count >= 1
      @courses.each do |course|
        if (course.classname == @student.classname) && (course.semester == @student.semester) && (course.year == @student.year.to_s)
          check = true
        end
      end
    end

    if not(check)
      course_hash = Course.new
      course_hash.classname = @student.classname
      course_hash.semester = @student.semester
      course_hash.year = @student.year
      course_hash.save
    end

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
     
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    @Images = Image.all
    @Courses = Course.all
    begin
    Student.import(params[:file], params[:year], params[:semester], params[:files], params[:classn])
    redirect_to students_path, notice: 'Students Imported Successfully'
    rescue
      redirect_to students_path, notice: "No file added"
    end
  end
  
  def help
  end

  def upload
  end

  def favor
    Student.favor(params[:lastname], params[:firstname], params[:uin], params[:email], params[:classname], params[:notes], params[:major], params[:finalgrade], params[:updatedgrade], params[:recletter], params[:semester], params[:year])
    redirect_back(fallback_location: root_path, notice: 'Student Favorited')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:email, :firstname, :lastname, :fullname, :notes, :uin, :major, :finalgrade,
                                    :updatedgrade, :classname, :recletter, :year, :semester, :image, :student)
  end
end


app/helpers/students_helper.rb
# frozen_string_literal: true

module StudentsHelper
end

app/views/students/edit.html.erb
<div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%; margin-bottom:3%;">
    <h1 style="text-align:center; font-size: 100px; color:#450012" class="text-uppercase">Editing student</h1>

</div>

<%= render 'form', student: @student %>


app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
  padding-bottom:0;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width:100%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
.new-student{
  margin-left: auto;
  margin-right: auto;
  text-align:center;
  padding-top: 3%;
  padding-bottom: 1%;
  color:#450012;
  
}

.main-body {
  padding: 15px;
  text-align:center;
    
}
.card {
  box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
  margin: 0 auto;
}

.card {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid #450012;
  border-radius: .25rem;
}

.card-body {
  flex: 1 1 auto;
  min-height: 1px;
  padding: 2rem;
}

.gutters-sm {
  margin-right: -8px;
  margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
  padding-right: 8px;
  padding-left: 8px;
}
.mb-3, .my-3 {
  margin-bottom: 1rem!important;
}

.bg-gray-300 {
  background-color: #e2e8f0;
}
.h-100 {
  height: 100%!important;
}
.shadow-none {
  box-shadow: none!important;
}
</style>
</head>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>






<body>


<div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%;margin-bottom:5%;">
  <h1 style="text-align:center; color:#450012" class="text-uppercase">Students Page</h1>
  <h3 style="text-align:center; color:#450012">View and search the list of students below</h3>
</div>

<div class="container">
  <h2 style="text-align: center;  color:#450012"> Filter Students </h2>
  <h4 style="text-align: center; margin-bottom: 1%; color:#450012"> Enter parameters below to filter students </h4>
</div>

<%= form_tag "/students", method: "GET" do %>
<div class="container">
    <div class="main-body">
          <div class="row">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <h6 class="mb-0">First Name</h6>
                    <div style="float:right" class="col text-secondary"> 
                      <%= text_field_tag :search_by_firstname, params[:search_by_firstname] %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <h6 class="mb-0">Last Name</h6>
                    <div class="col text-secondary">
                      <%= text_field_tag :search_by_lastname, params[:search_by_lastname] %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <h6 class="mb-0">Rec Letter</h6>
                    <div class="col text-secondary">
                      <%= text_field_tag :search_by_recletter, params[:search_by_recletter] %>
                    </div>
                  </div>
                </div>
              </div>
          </div>
        </div>
    </div>
<div style="text-align:center; margin-left:auto; margin-right:auto; margin-bottom: 2%">
  <%= submit_tag "Search", class: "btn buttonTo" %>

</div>
<% end %>

<div class="new-student container">
    <p style="font-size: 20px;">
      <%= link_to 'Upload file of students', upload_students_path, class: "btn buttonTo" %> or
      <%= link_to 'Add a new student', new_student_path, class: "btn buttonTo" %> 
    </p>
</div>
<div style="overflow-x:auto;">
  <table style="border:1px solid; border-color: #450012; width:90%; margin-bottom:5%;" class="center">
    <thead>
      <tr style="background-color: white; ">
        <th>Favorite</th>
        <th>Semester</th>
        <th>Year</th>
        <th>Email</th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Notes</th>
        <th>Uin</th>
        <th>Major</th>
        <th>Finalgrade</th>
        <th>Updatedgrade</th>
        <th>Classname</th>
        <th>Recletter</th>
        <th colspan="4">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @students.each do |student| %>
        <tr>
          <td><% if Favorite.all.where(uin: student.uin).find_each.count > 0 %>
             <span class="bi bi-star yellow-color"> </span>
             <% else %>
             <span class="bi bi-star" style="font-size:50px"> </span>
          <% end%> </td>
          <td><%= student.semester%></td>
          <td><%= student.year %></td>
          <td><%= student.email %></td>
          <td><%= student.firstname %></td>
          <td><%= student.lastname %></td>
          <td><%= student.notes %></td>
          <td><%= student.uin %></td>
          <td><%= student.major %></td>
          <td><%= student.finalgrade %></td>
          <td><%= student.updatedgrade %></td>
          <td><%= student.classname %></td>
          <td><%= student.recletter %></td>
          <% if Favorite.all.where(uin: student.uin, classname: student.classname, year: student.year, semester: student.semester).find_each.count == 0 %>
            <td><%= button_to 'Favorite', favor_students_path(:lastname => student.lastname, :firstname => student.firstname, :uin => student.uin, :email => student.email, :classname => student.classname, :notes => student.notes, :major => student.major, :finalgrade => student.finalgrade, :updatedgrade => student.updatedgrade, :recletter => student.recletter, :semester => student.semester, :year => student.year), :class => "btn buttonTo" %></td>
          <% else %>
            <td><%= button_to 'Unfavorite', favor_students_path(:lastname => student.lastname, :firstname => student.firstname, :uin => student.uin, :email => student.email, :classname => student.classname, :notes => student.notes, :major => student.major, :finalgrade => student.finalgrade, :updatedgrade => student.updatedgrade, :recletter => student.recletter, :semester => student.semester, :year => student.year), :class => "btn buttonTo" %></td>
          <% end%>
          <td><%= link_to 'Show', student, class: "btn buttonTo" %></td>
          <td><%= link_to 'Edit', edit_student_path(student), class: "btn buttonTo" %></td>
          <td><%= button_to "Delete", student, :method => "delete", :class => "btn buttonTo" %></td>
        </tr>
      <% end %> 
    </tbody>
</table>
</div>
<div class="footer">
	<p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
</div>

</body>

app/views/students/new.html.erb
<div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%; margin-bottom:3%;">
    <h1 style="text-align:center; font-size: 100px; color:#450012" class="text-uppercase">Create new student</h1>

</div>

<%= render 'form', student: @student %>


app/views/students/show.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
body{
    color: #1a202c;
    text-align: left;
    background-color: #ebe8df;   
    font-family: 'Montserrat';

}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
.main-body {
    padding: 15px;
}
.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid #450012;
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
</style>
</head>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>
<body>
<div class="main">


  <div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%; margin-bottom:3%;">
  <p class="notice" id="notice"><%= notice %></p>

    <h1 style="text-align:center; font-size: 100px; color:#450012" class="text-uppercase">Showing student</h1>

  </div>
  <div class="text-center">

    <h3 style="text-align:center; color:#450012">Current course: <%=@student.classname%></h3>

    <%= link_to 'Previous', @previous_student, class: "btn buttonTo" %>

    <%= link_to 'Next', @next_student, class: "btn buttonTo" %>
  </div>


<div class="container">
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    
                    <div class="container profile-picture">
                    <% begin %>
                      <% @Images.each do |image| %>
                        <% if @student.uin == image.uin  %>
                          <%= image_tag(image.photo, class: "style-image") %>
                          <% break %>
                        <% end %>
                      <% end %> 
                    <% rescue %>
                    
                    <% end %>
                    </div>

                    <div class="mt-3">
                      <h4><%= @student.firstname %> <%= @student.lastname %></h4>
                      <p class="text-secondary mb-1"><%= @student.major %></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card" style="margin-top:1%;">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                  <h4>Recommendation Letter Status</h4>
                    <div class="mt-1">
                      <h5 class="mb-4 text-uppercase"><%= @student.recletter %></h5>
                    </div>
                    
                  </div>
                </div>
              </div>

              <div class="card" style="margin-top:1%;">
                <div class="card-body">
                  <div class="d-flex flex-column">
                  <h6>Change Recommendation Letter Status</h6>
                    <div class="mt-1">
                      <%= form_with(model: @student) do |form| %>
                      <div class="field">
                        <%= form.select :recletter, ['YES', 'NO', 'UNDECIDED']%>
                      </div>
                      <div class="actions">
                        <%= form.submit class: 'btn buttonTo' %>
                      </div>
                    <%end%>
                    </div>
                  </div>
                </div>
              </div>

              <div class="card" style="margin-top:1%;">
                <div class="card-body">
                  <div class="d-flex flex-column">
                  <h4>Notes</h4>
                    <div class="mt-3">
                      <%= form_with(model: @student) do |form| %>
                        <div class="field">
                          <%= form.text_area :notes, :cols => "30", :rows => "10" %>
                        </div>
                        <div class="actions">
                          <%= form.submit class: 'btn buttonTo' %>
                        </div>
                      <%end%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.firstname %> <%= @student.lastname %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">UIN</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.uin %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Class</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.classname %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Semester and Year</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.semester %>, <%= @student.year %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Final Grade</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @student.finalgrade %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <%= link_to 'Edit Student Information', edit_student_path(@student) %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
    
    </div>
    <div class="footer">
      <p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
    </div>


</body>
</html>