config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :favorites

  resources :courses
  resources :images
  # root 'students#index'
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  get '/students/help' => 'students#help', as: :help
  get '/students/upload' => 'students#upload', as: :upload
  resources :students

  resources :students do
    get 'help', on: :collection
    get 'upload', on: :collection
  end

  resources :students do 
    collection { post :import }
  end

  resource :students do 
    member do
      post :favor
    end
  end

  resource :courses do 
    member do
      post :delc
    end
  end

  resources :images do 
    collection { post :import }
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1 or /courses/1.json
  def show
    @students = Student.all
    @favorites = Favorite.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delc
    Course.delc(params[:classname], params[:semester], params[:year])
    redirect_back(fallback_location: courses_path, notice: 'Course Deleted')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:classname, :semester, :year)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :classname %>
    <%= form.text_field :classname %>
  </div>

  <div class="field">
    <%= form.label :semester %>
    <%= form.text_field :semester %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<head>
<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width:100%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
.new-student{
  margin-left: auto;
  margin-right: auto;
  text-align:center;
  padding-top: 3%;
  padding-bottom: 1%;
  color:#450012;
  
}

.main-body {
  padding: 15px;
  text-align:center;
    
}
.card {
  box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
  margin: 0 auto;
}

.card {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid #450012;
  border-radius: .25rem;
}

.card-body {
  flex: 1 1 auto;
  min-height: 1px;
  padding: 2rem;
}

.gutters-sm {
  margin-right: -8px;
  margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
  padding-right: 8px;
  padding-left: 8px;
}
.mb-3, .my-3 {
  margin-bottom: 1rem!important;
}

.bg-gray-300 {
  background-color: #e2e8f0;
}
.h-100 {
  height: 100%!important;
}
.shadow-none {
  box-shadow: none!important;
}
footer {
	position: fixed;
	width: 100%;
	left: 0;
	bottom: 0;
	background-color: #450012;
	color: white;
	text-align: center;
}
</style>
</head>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>


<body>
<div class="main">

  <div style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%; margin-bottom: 5%;">
    <h1 style="text-align:center; color:#450012" class="text-uppercase">Courses Page</h1>
    <h3 style="text-align:center; color:#450012">View course rosters below</h3>
  </div>

<table style="border:1px solid; border-color: #450012; width:50%" class="center">
  <thead>
    <tr style="background-color: white; ">
      <th>Classname</th>
      <th>Semester</th>
      <th>Year</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.classname %></td>
        <td><%= course.semester %></td>
        <td><%= course.year %></td>
        <td><%= link_to 'Show', course, class: "btn buttonTo" %></td>
        <td><%= button_to 'Delete', delc_courses_path(:classname => course.classname,:semester => course.semester, :year => course.year), :class => "btn buttonTo" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="footer">
	<p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
</div>


</body>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb

<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"> 

<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width:100%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}

.dropbtn {
  background-color: #450012;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: #450012;}
</style>
</head>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>
<body>
<div class="main">

  <div style="background-color:white; width:100%;padding-bottom:8%;padding-top:8%; margin-bottom: 5%;">
    <p id="notice"><%= notice %></p>

    <h4 style="text-align:center; color:#450012">Class of</h4>
    <h1 style="text-align:center; color:#450012" class="text-uppercase"> <%= @course.classname %> </h1>
    <h3 style="text-align:center; color:#450012"><%= @course.semester %> <%= @course.year %> </h3>
  </div>

<table style="border:1px solid; border-color: #450012; width:90%; margin-bottom:5%;" class="center">
  <thead>
    <tr style="background-color: white; ">
      <th>Favorite</th>
      <th>Email</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Notes</th>
      <th>Uin</th>
      <th>Finalgrade</th>
      <th>Updatedgrade</th>
      <th>Recletter</th>
      <th colspan="4">Actions</th>
      <th>Multiple</th>
    </tr>
  </thead>
  

  <tbody>
    <% @students.where(classname: @course.classname, semester: @course.semester, year: @course.year).find_each do |student| %>
      <tr>
        <td><% if Favorite.all.where(uin: student.uin).find_each.count > 0 %>
             <span class="bi bi-star yellow-color"> </span>
             <% else %>
             <span class="bi bi-star" style="font-size:50px"> </span>
        <% end%> </td>
        <td><%= student.email %></td>
        <td><%= student.firstname %></td>
        <td><%= student.lastname %></td>
        <td><%= student.notes %></td>
        <td><%= student.uin %></td>
        <td><%= student.finalgrade %></td>
        <td><%= student.updatedgrade %></td>
        <td><%= student.recletter%></td>
        <% if Favorite.all.where(uin: student.uin, classname: student.classname, year: student.year, semester: student.semester).find_each.count == 0 %>
            <td><%= button_to 'Favorite', favor_students_path(:lastname => student.lastname, :firstname => student.firstname, :uin => student.uin, :email => student.email, :classname => student.classname, :notes => student.notes, :major => student.major, :finalgrade => student.finalgrade, :updatedgrade => student.updatedgrade, :recletter => student.recletter, :semester => student.semester, :year => student.year), :class => "btn buttonTo" %></td>
          <% else %>
            <td><%= button_to 'Unfavorite', favor_students_path(:lastname => student.lastname, :firstname => student.firstname, :uin => student.uin, :email => student.email, :classname => student.classname, :notes => student.notes, :major => student.major, :finalgrade => student.finalgrade, :updatedgrade => student.updatedgrade, :recletter => student.recletter, :semester => student.semester, :year => student.year), :class => "btn buttonTo" %></td>
        <% end%>
        <td><%= link_to 'Show', student, class: "btn buttonTo" %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn buttonTo" %></td>
        <td><%= button_to "Delete", student, :method => "delete", :class => "btn buttonTo" %></td>

        <td>
          <div class="dropdown">
            <button class="dropbtn">Courses</button>
            <div class="dropdown-content">
              <% if @students.where(uin: student.uin).count > 1 %>
                <% @students.where(uin: student.uin).find_each do |studentr| %>
                  <% if studentr.classname != student.classname %>
                    <%= studentr.semester %> <%= studentr.year %>, <%= studentr.classname %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </td>
      </tr>
      
    <% end %>
  </tbody>
</table>

</div>
<div class="footer">
	<p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
</div>
</body>