config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :favorites

  resources :courses
  resources :images
  # root 'students#index'
  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end

  get '/students/help' => 'students#help', as: :help
  get '/students/upload' => 'students#upload', as: :upload
  resources :students

  resources :students do
    get 'help', on: :collection
    get 'upload', on: :collection
  end

  resources :students do 
    collection { post :import }
  end

  resource :students do 
    member do
      post :favor
    end
  end

  resource :courses do 
    member do
      post :delc
    end
  end

  resources :images do 
    collection { post :import }
  end

  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :photo
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images or /images.json
  def index
    @images = Image.all
    @students = Student.all
  end

  # GET /images/1 or /images/1.json
  def show
    @students = Student.all
  end

  # GET /images/new
  def new
    @image = Image.new
    @students = Student.all
  end

  # GET /images/1/edit
  def edit
    @students = Student.all
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to image_url(@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    params[:files].each do |f|
      image_hash = Image.new
      # need to access the temprary data and get the (#)+1's uin
      image_hash.uin = (f.original_filename.to_s)[0..-9]
      image_hash.photo.attach(f)
      image_hash.save
    end
    redirect_to images_path, notice: 'Images Imported Successfully'
  rescue StandardError
    redirect_to images_path, notice: 'No Image uploaded.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:uin, :photo, files: [])
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uin %>
    <%= form.text_field :uin %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, multiple= true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>


app/views/images/index.html.erb


<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"> 

<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
  min-height:100%;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width: 80%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
</style>
</head>
<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Favorites', favorites_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Images', images_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
</nav>


<body>
<div class="main">
  <div class="text-center" style="background-color:white; width:100%; padding-top:8%;padding-bottom:8%;margin-bottom:5%;">
    <p id="notice"><%= notice %></p>

    <h1 style="text-align:center; color:#450012" class="text-uppercase">Images Page</h1>
    <h3 style="text-align:center; color:#450012">View uploaded images</h3>
  </div>

<table style="border:1px solid; border-color: #450012; width:20%" class="center">
  <thead>
    <tr style="background-color: white; ">
      <th>UIN</th>
      <th colspan="2" style="width:50%">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.uin %></td>
        <td><%= button_to "Delete", image, :method => "delete", :class => "btn buttonTo" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<div class="footer">
	<p>CSCE Recommendation Tracker for Dr. Lightfoot. Created by Jonathan Le, Yash Kalyani, Calvin Nguyen, and Mihiran Pandey.</p>
</div>

</body>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<style>
body {
  margin:0;
  font-family: 'Montserrat';
  background-color: #ebe8df;
  min-height:100%;
}
h1{
  font-size: 100px;
}
h2{
  font-size: 30px;
}
h3{
  font-size: 40px;
}
h4{
  font-size: 20px;
}
.center {
  margin-left: auto;
  margin-right: auto;
  width: 80%;
  text-align:center;
}
th {
  background: #450012;
  color:white;
  
}
tr:nth-child(odd) {
  background-color: #F5D5CB;
}
nav{
  background-color: #450012;
}
.navbar .navbar-nav .nav-link:hover {
  background-color: #450012;
  color: #fff;
}
</style>
</head>

<nav class="navbar fixed-top navbar-expand-sm navbar-dark">
  <div class="container-fluid">
    <a style="background-color:transparent;" class="navbar-brand" href="#">CSCE Recommendation Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Students', students_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Courses', courses_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Images', images_path, class: 'nav-link' %>
        </li>
        <li class="nav-item ">
          <%= link_to "Help Page", help_students_path, class: 'nav-link' %>
        </li>  
        <li class="nav-item ms-auto">
          <%= link_to "Sign Out", destroy_admin_session_path, class: 'nav-link' %>
        </li>  
      </ul>
    </div>
  </div>
</nav>

<p id="notice"><%= notice %></p>

<p>
  <strong>Uin:</strong>
  <%= @image.uin %>
</p>


<p>
  <strong>Photo:</strong>
  <%= image_tag(@image.photo)%>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>